### ISSUE TITLE
Users have positive bill error

### ISSUE THREAD

**Issue by aandrey1993** [SergheiBejenari/cucumberScenario#2]
Первый же сценарий `Users have positive bill` проваливается с данной ошибкой:

![изображение](https://user-images.githubusercontent.com/49781313/115872024-fc749a00-a449-11eb-9c39-aa9788ed2a5a.png)

```
Element info: {Using=xpath, value=//input[contains(@name,'UserId')]}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy14.clear(Unknown Source)
	at steps.CommonSteps.logInUser(CommonSteps.java:26)
	at steps.TransferFundsStepTest.usersHavePositiveBill(TransferFundsStepTest.java:34)
```

Попробуйте, пожалуйста, разобраться с причиной ошибки и скажите как её можно решить.

**Comment by SergheiBejenari** [comment]
Так как задание не подразумевало запуск сценария я не стал углубляться в проблему при решении задания.
Проблема была в том что Webdriver не переходил на новую вкладку. 
Эта проблема была так же устранена.
